/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje2;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nesma
 */
public class Frm_Admin extends javax.swing.JFrame {

    DefaultTableModel tbl_team_model;
    public static DefaultTableModel tbl_match_model;

    /**
     * Creates new form NewJFrame
     */
    public Frm_Admin() {
        initComponents();
        tbl_team_model = new DefaultTableModel();//tablo üzerinde işlem yapabilmek için table model tanımlanır
        tbl_team_model.setColumnIdentifiers(new Object[]{"ID", "TEAM NAME", "COACH"});
        tbl_team.setModel(tbl_team_model);
        tbl_match_model = new DefaultTableModel();
        tbl_match_model.setColumnIdentifiers(new Object[]{"ID", "TEAM", "TEAM", "WEEK", "TIME", "SCORE"});
        tbl_match.setModel(tbl_match_model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tppdpane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        spltpnl_teams = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_team = new javax.swing.JTable();
        txt_searchTeam = new javax.swing.JTextField();
        btn_searchTeam = new javax.swing.JButton();
        btn_allTeam = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_teamName = new javax.swing.JLabel();
        txt_teamName = new javax.swing.JTextField();
        lbl_coachName = new javax.swing.JLabel();
        txt_coachName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        spltpnl_matches = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        btn_searchMatch = new javax.swing.JButton();
        txt_searchMatchOrWeek = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_match = new javax.swing.JTable();
        btn_showallmatches = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spnr_week = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        cmbx_time = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtf_score = new javax.swing.JFormattedTextField();
        btn_selectTeams = new javax.swing.JButton();
        txt_team1 = new javax.swing.JTextField();
        txt_team2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_teams = new javax.swing.JMenu();
        mntm_addTeam = new javax.swing.JMenuItem();
        mntm_deleteTeam = new javax.swing.JMenuItem();
        mntm_updateTeam = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mntm_exit1 = new javax.swing.JMenuItem();
        mn_matches = new javax.swing.JMenu();
        mntm_addMatch = new javax.swing.JMenuItem();
        mntm_deleteMatch = new javax.swing.JMenuItem();
        mntm_updateMatch = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mntm_exit2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(966, 548));
        setMinimumSize(new java.awt.Dimension(966, 548));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        spltpnl_teams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spltpnl_teamsMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(700, 581));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 581));

        tbl_team.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "TEAM NAME", "COACH"
            }
        ));
        tbl_team.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_teamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_team);

        txt_searchTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchTeamActionPerformed(evt);
            }
        });

        btn_searchTeam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_searchTeam.setText("SEARCH TEAM");
        btn_searchTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchTeamActionPerformed(evt);
            }
        });

        btn_allTeam.setBackground(new java.awt.Color(153, 204, 255));
        btn_allTeam.setText("SHOW ALL TEAM");
        btn_allTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_searchTeam)
                                .addGap(18, 18, 18)
                                .addComponent(btn_searchTeam))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btn_allTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchTeam))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_allTeam, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        spltpnl_teams.setLeftComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(288, 581));
        jPanel4.setMinimumSize(new java.awt.Dimension(288, 581));

        lbl_teamName.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_teamName.setText("Team Name");

        lbl_coachName.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_coachName.setText("Coach Name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_teamName, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(txt_coachName)
                        .addComponent(lbl_teamName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_coachName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(lbl_teamName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_teamName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(lbl_coachName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_coachName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        spltpnl_teams.setRightComponent(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(spltpnl_teams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(spltpnl_teams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tppdpane.addTab("SHOW TEAMS", jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        spltpnl_matches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spltpnl_matchesMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 102, 0));
        jPanel5.setMaximumSize(new java.awt.Dimension(700, 581));
        jPanel5.setMinimumSize(new java.awt.Dimension(700, 581));

        btn_searchMatch.setText("SEARCH");
        btn_searchMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchMatchActionPerformed(evt);
            }
        });

        txt_searchMatchOrWeek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tbl_match.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TEAM", "TEAM", "WEEK", "TIME", "SCORE"
            }
        ));
        tbl_match.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_matchMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_match);

        btn_showallmatches.setBackground(new java.awt.Color(153, 204, 0));
        btn_showallmatches.setText("SHOW ALL MATCHES");
        btn_showallmatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showallmatchesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btn_showallmatches, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txt_searchMatchOrWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_searchMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(btn_searchMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_searchMatchOrWeek, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_showallmatches, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        spltpnl_matches.setLeftComponent(jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 0));
        jPanel6.setMaximumSize(new java.awt.Dimension(288, 581));
        jPanel6.setMinimumSize(new java.awt.Dimension(288, 581));
        jPanel6.setPreferredSize(new java.awt.Dimension(288, 581));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Match Week :");

        spnr_week.setModel(new javax.swing.SpinnerNumberModel(1, 1, 36, 1));
        spnr_week.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Match Time :");

        cmbx_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Score :");

        try {
            txtf_score.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_selectTeams.setText("SELECT TEAMS");
        btn_selectTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectTeamsActionPerformed(evt);
            }
        });

        txt_team1.setEditable(false);

        txt_team2.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("First Team :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Second Team :");

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnr_week, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_team2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtf_score, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbx_time, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)))))
                        .addGap(41, 41, 41))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_team1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selectTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btn_selectTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_team1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_team2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spnr_week, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbx_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        spltpnl_matches.setRightComponent(jPanel6);

        jPanel2.add(spltpnl_matches);

        tppdpane.addTab("SHOW MATCHES", jPanel2);

        getContentPane().add(tppdpane);

        mn_teams.setText("Teams");

        mntm_addTeam.setText("Add Team");
        mntm_addTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_addTeamActionPerformed(evt);
            }
        });
        mn_teams.add(mntm_addTeam);

        mntm_deleteTeam.setText("Delete Team");
        mntm_deleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_deleteTeamActionPerformed(evt);
            }
        });
        mn_teams.add(mntm_deleteTeam);

        mntm_updateTeam.setText("Update Team");
        mntm_updateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_updateTeamActionPerformed(evt);
            }
        });
        mn_teams.add(mntm_updateTeam);
        mn_teams.add(jSeparator1);

        mntm_exit1.setText("Exit");
        mntm_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_exit1ActionPerformed(evt);
            }
        });
        mn_teams.add(mntm_exit1);

        jMenuBar1.add(mn_teams);

        mn_matches.setText("Matches");

        mntm_addMatch.setText("Add Match");
        mntm_addMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_addMatchActionPerformed(evt);
            }
        });
        mn_matches.add(mntm_addMatch);

        mntm_deleteMatch.setText("Delete Match");
        mntm_deleteMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_deleteMatchActionPerformed(evt);
            }
        });
        mn_matches.add(mntm_deleteMatch);

        mntm_updateMatch.setText("Update Match");
        mntm_updateMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_updateMatchActionPerformed(evt);
            }
        });
        mn_matches.add(mntm_updateMatch);
        mn_matches.add(jSeparator2);

        mntm_exit2.setText("Exit");
        mntm_exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_exit1ActionPerformed(evt);
            }
        });
        mn_matches.add(mntm_exit2);

        jMenuBar1.add(mn_matches);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_teamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_teamMouseClicked
        if (tbl_team.getSelectedRow() < 0) {//tablo üzerinde seçili satır yoksa return edilir
            return;
        }
        int id = (int) tbl_team_model.getValueAt(tbl_team.getSelectedRow(), 0);//Seçili olan takımın id'si alınır
        Team t1 = DB_Team_Management.SearchTeamById(id);//id'den takım bulunur
        if (t1 != null) {
            txt_teamName.setText(t1.name);
            txt_coachName.setText(t1.coach);

        }

    }//GEN-LAST:event_tbl_teamMouseClicked

    private void btn_searchTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchTeamActionPerformed
        String search = txt_searchTeam.getText().toUpperCase();
        boolean isFounded = false;
        boolean isFull = false;

        if (search.compareTo("") == 0) {//Hiçbir şey yazılmamışsa uyarı mesajı verilir
            JOptionPane.showMessageDialog(rootPane, "Please write a team name");
            isFull = true;
        } else {
            tbl_team_model.setRowCount(0);
            ArrayList<Team> tlist = DB_Team_Management.SearchByTeamName(search);
            for (Team tm1 : tlist) {
                tbl_team_model.addRow(new Object[]{tm1.id, tm1.name, tm1.coach});//Aranan özellikteki takımlar tabloya getirilir
                isFounded = true;
                txt_teamName.setText(tm1.name);
                txt_coachName.setText(tm1.coach);
            }
        }

        if (!isFounded & !isFull) {//Boş değilse ve aranan özellikte bir takım bulunamadıysa 
            JOptionPane.showMessageDialog(rootPane, "Team not founded");

        }

    }//GEN-LAST:event_btn_searchTeamActionPerformed

    private void btn_allTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allTeamActionPerformed
        tbl_team_model.setRowCount(0);
        ArrayList<Team> tlist = DB_Team_Management.GetTeams();//Veritabanındaki tüm takımlar getirilir

        for (Team tm1 : tlist) {
            tbl_team_model.addRow(new Object[]{tm1.id, tm1.name, tm1.coach});

        }
    }//GEN-LAST:event_btn_allTeamActionPerformed

    private void mntm_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntm_exit1ActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to close page?", "Closing", JOptionPane.YES_NO_OPTION);
        switch (option) {
            case JOptionPane.YES_OPTION:
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;

        }
    }//GEN-LAST:event_mntm_exit1ActionPerformed

    private void mntm_updateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntm_updateTeamActionPerformed
        try {
            Pattern pattern = Pattern.compile("^([a-z]|[A-Z]|[ÖÇİŞÜĞöçşığü]){2,45}$");
            Matcher matcher = pattern.matcher(txt_teamName.getText());
            if (!matcher.find()) {

                throw new Exception("Invalid team name ");
            }

            pattern = Pattern.compile("^([a-z]|[A-Z]|[ÖÇİŞÜĞöçşığü]){2,15}\s{1}([a-z]|[A-Z]|[ÖÇİŞÜĞöçşığü]){2,15}$");
            matcher = pattern.matcher(txt_coachName.getText());
            if (!matcher.find()) {

                throw new Exception("Invalid coach name ");
            }

            int rowindex = tbl_team.getSelectedRow();
            boolean isSelected = true;
            if (rowindex != -1) {//Seçili satır varsa

                Team tm1 = new Team();
                tm1.id = Integer.parseInt(tbl_team_model.getValueAt(rowindex, 0).toString());
                tm1.name = txt_teamName.getText().toUpperCase();
                tm1.coach = txt_coachName.getText().toUpperCase();

                if (DB_Team_Management.UpdateTeam(tm1) & !(txt_teamName.getText().compareTo("") == 0 || txt_coachName.getText().compareTo("") == 0)) {
                    JOptionPane.showMessageDialog(rootPane, "Team updated");
                    tbl_team_model.setValueAt(tm1.id, rowindex, 0);//Değiştirilen özellikler model üzerinden tabloda değiştirilir
                    tbl_team_model.setValueAt(tm1.name, rowindex, 1);
                    tbl_team_model.setValueAt(tm1.coach, rowindex, 2);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Team not updated");
                }
            } else {//Seçili takım yoksa

                JOptionPane.showMessageDialog(rootPane, "Please select the team you want to update");
                isSelected = false;
            }
            if (isSelected) {
                if (txt_teamName.getText().compareTo("") == 0 || txt_coachName.getText().compareTo("") == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Please fill all fields");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_mntm_updateTeamActionPerformed

    private void mntm_addTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntm_addTeamActionPerformed
        try {
            Pattern pattern = Pattern.compile("^([a-z]|[A-Z]|[ÖÇİŞÜĞöçşığü]){2,45}$");
            Matcher matcher = pattern.matcher(txt_teamName.getText());
            if (!matcher.find()) {

                throw new Exception("Invalid team name ");
            }

            pattern = Pattern.compile("^([a-z]|[A-Z]|[ÖÇİŞÜĞöçşığü]){2,15}\s{1}([a-z]|[A-Z]|[ÖÇİŞÜĞöçşığü]){2,15}$");
            matcher = pattern.matcher(txt_coachName.getText());
            if (!matcher.find()) {

                throw new Exception("Invalid coach name ");
            }

            Team tm1 = new Team();

            tm1.name = txt_teamName.getText().toUpperCase();
            tm1.coach = txt_coachName.getText().toUpperCase();

            if (DB_Team_Management.AddTeam(tm1)) {//Oluşturulan takım nesnesi fonksiyon içerisine gönderilir
                JOptionPane.showMessageDialog(rootPane, "Team Added");
                int id = DB_Team_Management.SearchTeamByName(tm1.name).id;

                tbl_team_model.addRow(new Object[]{id, txt_teamName.getText().toUpperCase(), txt_coachName.getText().toUpperCase()});
                txt_teamName.setText("");
                txt_coachName.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Team not added");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_mntm_addTeamActionPerformed

    private void mntm_deleteTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntm_deleteTeamActionPerformed

        int rowindex = tbl_team.getSelectedRow();

        if (rowindex != -1) {//Seçili satır varsa
            int id = Integer.parseInt(tbl_team_model.getValueAt(rowindex, 0).toString());

            if (DB_Team_Management.DeleteTeamById(id)) {//Seçili olan satır takım id'sinden silinir
                JOptionPane.showMessageDialog(rootPane, "Team deleted");
                tbl_team_model.removeRow(rowindex);
                txt_teamName.setText("");
                txt_coachName.setText("");
            }
        } else {//Seçili satır yoksa
            JOptionPane.showMessageDialog(rootPane, "Please select the team you want to delete");
        }
    }//GEN-LAST:event_mntm_deleteTeamActionPerformed


    private void btn_selectTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectTeamsActionPerformed

        Pattern pattern = Pattern.compile("^([0-9]){1}-{1}[0-9]{1}$");
        Matcher matcher = pattern.matcher(txtf_score.getText());
        if (!matcher.find()) {

            JOptionPane.showMessageDialog(rootPane, "Invalid score");
        } else {
            Match m1 = new Match();//Eklenecek olan maçın özellikleri text alanlarındaki bilgilerden alınır

            m1.week = Integer.parseInt(spnr_week.getValue().toString());
            m1.time = cmbx_time.getSelectedItem().toString();
            m1.score = txtf_score.getText();
            Frm_Teams fr = new Frm_Teams(m1);
            fr.setVisible(true);//Frm_Teams açılır

        }

    }//GEN-LAST:event_btn_selectTeamsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<Team> teams = DB_Team_Management.GetTeams();//Frame açılırken veritabanındaki takımlar tabloya getirilir

        for (Team team : teams) {

            tbl_team_model.addRow(new Object[]{team.id, team.name, team.coach});
        }
        ArrayList<Match> matches = DB_Match_Management.GetMatches();//Frame açılırken veritabanındaki maçlar tabloya getirilir

        for (Match match : matches) {
            tbl_match_model.addRow(new Object[]{match.id, match.first_team, match.second_team, match.week, match.time, match.score});
        }


    }//GEN-LAST:event_formWindowOpened

    private void btn_showallmatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showallmatchesActionPerformed
        tbl_match_model.setRowCount(0);
        ArrayList<Match> mlist = DB_Match_Management.GetMatches();//Veritabanındaki tüm maçlar getirilir

        for (Match match : mlist) {
            tbl_match_model.addRow(new Object[]{match.id, match.first_team, match.second_team, match.week, match.time, match.score});
        }
    }//GEN-LAST:event_btn_showallmatchesActionPerformed

    private void mntm_deleteMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntm_deleteMatchActionPerformed
        int rowindex = tbl_match.getSelectedRow();

        if (rowindex != -1) {//Seçili maç varsa
            int id = Integer.parseInt(tbl_match_model.getValueAt(rowindex, 0).toString());
            if (DB_Match_Management.DeleteMatchById(id)) {//Seçili olan maç id'sinden silinir
                JOptionPane.showMessageDialog(rootPane, "Match deleted");
                tbl_match_model.removeRow(rowindex);
                txt_team1.setText("");
                txt_team2.setText("");
                spnr_week.setValue(1);
                cmbx_time.setSelectedIndex(0);
                txtf_score.setText("");

            }
        } else {//Seçili maç yoksa
            JOptionPane.showMessageDialog(rootPane, "Please select the match you want to delete");
        }
    }//GEN-LAST:event_mntm_deleteMatchActionPerformed

    private void tbl_matchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_matchMouseClicked
        if (tbl_match.getSelectedRow() < 0) {//Seçili satır yoksa return edilir
            return;
        }
        int id = (int) tbl_match_model.getValueAt(tbl_match.getSelectedRow(), 0);
        Match m1 = DB_Match_Management.SearchMatchById(id);//İd'den maç bulunur
        if (m1 != null) {
            txt_team1.setText(m1.first_team);//Bulunan maçın bilgileri getirilir
            txt_team2.setText(m1.second_team);
            spnr_week.setValue(m1.week);
            cmbx_time.setSelectedItem(m1.time);
            txtf_score.setText(m1.score);

        }
    }//GEN-LAST:event_tbl_matchMouseClicked

    private void btn_searchMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchMatchActionPerformed
        String search = txt_searchMatchOrWeek.getText().toUpperCase();

        boolean isFounded = false;
        boolean isFull = false;
        if (search.compareTo("") == 0) {//Hiçbir şey yazılmamışsa uyarı mesaı verilir
            JOptionPane.showMessageDialog(rootPane, "Please write a team name or match week");
            isFull = true;
        } else {
            tbl_match_model.setRowCount(0);
            ArrayList<Match> mlist = DB_Match_Management.SearchByMatchNameOrWeek(search);
            for (Match m1 : mlist) {
                tbl_match_model.addRow(new Object[]{m1.id, m1.first_team, m1.second_team, m1.week, m1.time, m1.score});//Aranan özellikteki maçlar tabloya getirilir
                isFounded = true;

            }
        }

        if (!isFounded & !isFull) {//Boş değilse ve aranan özellikte bir maç bulunamadıysa
            JOptionPane.showMessageDialog(rootPane, "Match not founded");

        }
    }//GEN-LAST:event_btn_searchMatchActionPerformed

    private void mntm_updateMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntm_updateMatchActionPerformed
        try {
            Pattern pattern = Pattern.compile("^([a-z]|[A-Z]|[ÖÇİŞÜĞöçşığü]){2,45}$");
            Matcher matcher = pattern.matcher(txt_team1.getText());
            if (!matcher.find()) {

                throw new Exception("Invalid team name ");
            }

            matcher = pattern.matcher(txt_team2.getText());
            if (!matcher.find()) {

                throw new Exception("Invalid team name ");
            }

            int rowindex = tbl_match.getSelectedRow();
            if (rowindex != -1) {//Seçili maç varsa

                Match m1 = new Match();
                m1.id = Integer.parseInt(tbl_match_model.getValueAt(rowindex, 0).toString());
                m1.first_team = txt_team1.getText();
                m1.second_team = txt_team2.getText();
                m1.week = Integer.parseInt(spnr_week.getValue().toString());
                m1.time = cmbx_time.getSelectedItem().toString();
                m1.score = txtf_score.getText();

                if (DB_Match_Management.UpdateMatch(m1)) {
                    JOptionPane.showMessageDialog(rootPane, "Match updated");
                    tbl_match_model.setValueAt(m1.id, rowindex, 0);//Değiştirilen özellikler model üzerinden tabloda değiştirilir
                    tbl_match_model.setValueAt(m1.first_team, rowindex, 1);
                    tbl_match_model.setValueAt(m1.second_team, rowindex, 2);
                    tbl_match_model.setValueAt(m1.week, rowindex, 3);
                    tbl_match_model.setValueAt(m1.time, rowindex, 4);
                    tbl_match_model.setValueAt(m1.score, rowindex, 5);

                    txt_team1.setText("");
                    txt_team2.setText("");
                    spnr_week.setValue(1);
                    cmbx_time.setSelectedIndex(0);
                    txtf_score.setText("");

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Match not updated");
                }
            } else {//Seçili maç yoksa
                JOptionPane.showMessageDialog(rootPane, "Please select the match you want to update");

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_mntm_updateMatchActionPerformed

    private void spltpnl_teamsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spltpnl_teamsMouseClicked
        JPopupMenu pm = new JPopupMenu();
        //PopupMenü oluşturularak menuitemlar eklenir.
        JMenuItem mn_add = new JMenuItem("Add");
        JMenuItem mn_delete = new JMenuItem("Delete");
        JMenuItem mn_update = new JMenuItem("Update");

        pm.add(mn_add);
        pm.add(mn_delete);
        pm.add(mn_update);

        mn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_addTeamActionPerformed(evt);
            }
        });

        mn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_deleteTeamActionPerformed(evt);
            }
        });
        mn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_updateTeamActionPerformed(evt);
            }
        });

        pm.show(this, evt.getX(), evt.getY());


    }//GEN-LAST:event_spltpnl_teamsMouseClicked

    private void mntm_addMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntm_addMatchActionPerformed
        Pattern pattern = Pattern.compile("^([0-9]){1}-{1}[0-9]{1}$");
        Matcher matcher = pattern.matcher(txtf_score.getText());
        if (!matcher.find()) {

            JOptionPane.showMessageDialog(rootPane, "Invalid score");
        } else {
            Match m1 = new Match();
            //Eklenecek olan maçın özellikleri text alanlarındaki bilgilerden alınır
            m1.week = Integer.parseInt(spnr_week.getValue().toString());
            m1.time = cmbx_time.getSelectedItem().toString();
            m1.score = txtf_score.getText();
            Frm_Teams fr = new Frm_Teams(m1);
            fr.setVisible(true);//Frm_Teams açılır
        }
    }//GEN-LAST:event_mntm_addMatchActionPerformed

    private void spltpnl_matchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spltpnl_matchesMouseClicked
        JPopupMenu pm = new JPopupMenu();
        //PopupMenü oluşturularak menuitemlar eklenir.
        JMenuItem mn_add = new JMenuItem("Add");
        JMenuItem mn_delete = new JMenuItem("Delete");
        JMenuItem mn_update = new JMenuItem("Update");

        pm.add(mn_add);
        pm.add(mn_delete);
        pm.add(mn_update);

        mn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_addMatchActionPerformed(evt);
            }
        });

        mn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_deleteMatchActionPerformed(evt);
            }
        });
        mn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntm_updateMatchActionPerformed(evt);
            }
        });

        pm.show(this, evt.getX(), evt.getY());
    }//GEN-LAST:event_spltpnl_matchesMouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_team1.setText("");
        txt_team2.setText("");
        spnr_week.setValue(1);
        cmbx_time.setSelectedIndex(0);
        txtf_score.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_searchTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchTeamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_allTeam;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_searchMatch;
    private javax.swing.JButton btn_searchTeam;
    private javax.swing.JButton btn_selectTeams;
    private javax.swing.JButton btn_showallmatches;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbx_time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbl_coachName;
    private javax.swing.JLabel lbl_teamName;
    private javax.swing.JMenu mn_matches;
    private javax.swing.JMenu mn_teams;
    private javax.swing.JMenuItem mntm_addMatch;
    private javax.swing.JMenuItem mntm_addTeam;
    private javax.swing.JMenuItem mntm_deleteMatch;
    private javax.swing.JMenuItem mntm_deleteTeam;
    private javax.swing.JMenuItem mntm_exit1;
    private javax.swing.JMenuItem mntm_exit2;
    private javax.swing.JMenuItem mntm_updateMatch;
    private javax.swing.JMenuItem mntm_updateTeam;
    private javax.swing.JSplitPane spltpnl_matches;
    private javax.swing.JSplitPane spltpnl_teams;
    private javax.swing.JSpinner spnr_week;
    private javax.swing.JTable tbl_match;
    private javax.swing.JTable tbl_team;
    private javax.swing.JTabbedPane tppdpane;
    private javax.swing.JTextField txt_coachName;
    private javax.swing.JTextField txt_searchMatchOrWeek;
    private javax.swing.JTextField txt_searchTeam;
    private javax.swing.JTextField txt_team1;
    private javax.swing.JTextField txt_team2;
    private javax.swing.JTextField txt_teamName;
    private javax.swing.JFormattedTextField txtf_score;
    // End of variables declaration//GEN-END:variables
}
