/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje2;

import static com.mycompany.proje2.Frm_Admin.tbl_match_model;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.html.HTML.Attribute.ID;

/**
 *
 * @author nesma
 */
public class Frm_Teams extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Teams
     */
    DefaultListModel lst_teams_model;

    Match match;

    public Frm_Teams(Match match) {//Referans olarak bir takım alınır
        initComponents();
        this.match = match;

        SetTeamToList();//Frame açılırken tüm takımlar listelenir
    }

    private void SetTeamToList() {
        DefaultListModel<String> lst_teams_model = new DefaultListModel<>();
        lst_teams.setModel(lst_teams_model);

        ArrayList<Team> teams = DB_Team_Management.GetTeams();

        for (Team team : teams) {

            lst_teams_model.addElement(team.name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_teams = new javax.swing.JList<>();
        btn_firstTeam = new javax.swing.JButton();
        txt_firstTeam = new javax.swing.JTextField();
        btn_secondTeam = new javax.swing.JButton();
        txt_secondTeam = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        lst_teams.setBackground(new java.awt.Color(153, 204, 255));
        lst_teams.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lst_teams);

        btn_firstTeam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_firstTeam.setText("Select First Team");
        btn_firstTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstTeamActionPerformed(evt);
            }
        });

        txt_firstTeam.setEditable(false);

        btn_secondTeam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_secondTeam.setText("Select Second Team");
        btn_secondTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secondTeamActionPerformed(evt);
            }
        });

        txt_secondTeam.setEditable(false);

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_firstTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_firstTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_secondTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_secondTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_firstTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txt_firstTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_secondTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_secondTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btn_firstTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstTeamActionPerformed

        if (lst_teams.getSelectedIndex() < 0) {
            return;
        }
        String name = lst_teams.getSelectedValue();
        if (name.compareTo(txt_secondTeam.getText()) == 0) {//Aynı iki takımın seçilmemesi için

            JOptionPane.showMessageDialog(rootPane, "Please select another team");

        } else {
            Team t1 = DB_Team_Management.SearchTeamByName(name);
            if (t1 != null) {
                txt_firstTeam.setText(t1.name);

            }

        }
    }//GEN-LAST:event_btn_firstTeamActionPerformed

    private void btn_secondTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secondTeamActionPerformed
        if (lst_teams.getSelectedIndex() < 0) {
            return;
        }
        String name = lst_teams.getSelectedValue();
        if (name.compareTo(txt_firstTeam.getText()) == 0) {//Aynı iki takımın seçilmemesi için
            JOptionPane.showMessageDialog(rootPane, "Please select another team");

        } else {
            Team t1 = DB_Team_Management.SearchTeamByName(name);
            if (t1 != null) {
                txt_secondTeam.setText(t1.name);

            }

        }
    }//GEN-LAST:event_btn_secondTeamActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        this.match.first_team = txt_firstTeam.getText();//Referans olarak alınan maçın ilk takımı
        this.match.second_team = txt_secondTeam.getText();//Referans olarak alınan maçın ikinci takımı

        if (txt_firstTeam.getText().compareTo("") == 0 || txt_secondTeam.getText().compareTo("") == 0) {//Herhangi bir alan boşsa
            JOptionPane.showMessageDialog(rootPane, "Please select two teams");

        } else if (DB_Match_Management.AddMatch(this.match)) {

            tbl_match_model.setRowCount(0);
            ArrayList<Match> mlist = DB_Match_Management.GetMatches();

            for (Match match : mlist) {
                tbl_match_model.addRow(new Object[]{match.id, match.first_team, match.second_team, match.week, match.time, match.score});
            }

            JOptionPane.showMessageDialog(rootPane, "Match Added");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Match not added");

        }
        
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_firstTeam;
    private javax.swing.JButton btn_secondTeam;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst_teams;
    private javax.swing.JTextField txt_firstTeam;
    private javax.swing.JTextField txt_secondTeam;
    // End of variables declaration//GEN-END:variables
}
